In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest

In [2]:
df = pd.read_excel("..\Data\Preprocessed\\train_data.xlsx")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11309 entries, 0 to 11308
Columns: 151 entries, ofd_date to week_no
dtypes: datetime64[ns](1), int64(150)
memory usage: 13.0 MB

In [4]:
def outlier_point_highlight(cols, outlier_indices):
    cols = cols.transpose()
    outlier_indices = outlier_indices.transpose()
    outliers = np.empty(cols.shape)
    outliers[:,:] = np.nan
    for i,col in enumerate(cols):
        for j,outlier_index in enumerate(outlier_indices):
            if outlier_index == -1:
                outliers[i,j] = cols[i,j]
    return outliers

In [5]:
cols = df.columns[2:10]
outlier_indices = IsolationForest(contamination=0.03).fit_predict(df[cols].values)
outliers = outlier_point_highlight(df[cols].values, outlier_indices)
for (outlier, col) in zip(outliers,cols):
    df[col] = df[col].where(~df[col].isin(outlier), np.nan)

In [6]:
df = df.dropna().reset_index()

In [7]:
df

,index,ofd_date,OFD,Slam,Earlies_Exp,Earlies_Rec,MNR_SNR_Exp,Rollover,Returns,R_Sideline,...,Delivery_D75,Delivery_D76,Delivery_D77,Delivery_D78,Delivery_D79,Delivery_D8,Delivery_D80,Delivery_D9,weekday,week_no
0,29,2021-02-01,33052,31034.0,666.0,1684.0,287.0,320.0,1304.0,1624.0,...,1,0,0,0,0,0,0,0,0,5
1,31,2021-02-01,4063,2499.0,181.0,20.0,3.0,550.0,79.0,1012.0,...,0,0,0,0,0,0,0,0,0,5
2,140,2021-02-02,19744,18908.0,1442.0,512.0,95.0,79.0,75.0,36.0,...,0,0,0,0,0,0,0,0,1,5
3,202,2021-02-03,32537,32816.0,1929.0,1466.0,363.0,164.0,208.0,678.0,...,0,0,0,0,0,0,0,0,2,5
4,279,2021-02-04,30324,29444.0,1124.0,1594.0,452.0,363.0,205.0,1676.0,...,0,0,0,0,0,0,0,0,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,11065,2021-06-27,5730,6039.0,1010.0,392.0,73.0,15.0,82.0,353.0,...,0,0,0,0,0,0,0,0,6,25
343,11107,2021-06-28,9400,9443.0,4.0,139.0,957.0,1144.0,283.0,694.0,...,0,0,0,0,0,0,0,0,0,26
344,11110,2021-06-28,25371,23559.0,721.0,1065.0,309.0,235.0,661.0,1786.0,...,0,0,0,0,0,0,0,0,0,26
345,11125,2021-06-28,13851,12804.0,206.0,1014.0,57.0,188.0,516.0,1267.0,...,0,0,0,0,0,0,0,0,0,26
346,11172,2021-06-29,12635,12589.0,703.0,257.0,138.0,57.0,364.0,17.0,...,0,0,0,1,0,0,0,0,1,26

As we can see, trying to remove all outliers simultaneously from the entire dataframe using this method removes far too many elements, hence the previous method was most appropriate